# school_system_parameters

# Parameters
MAX_PART_TIME_STUDENT_COURSES = 2
MAX_NUMBER_OF_COURSES_PER_STUDENT = 6
PROFESSOR_COURSE_THRESHOLD_FOR_BONUS = 4
COURSE_GRADE_RANGE = 100
ACADEMIC_PROBATION_RATIO = 60 / 100
